# Generated by Django 4.2.7 on 2023-12-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Precio', models.IntegerField()),
                ('Stock', models.IntegerField()),
                ('Descripcion', models.CharField(max_length=200)),
            ],
        ),
    ]
